name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install gcc10
      run: sudo apt install g++-10
    - name: install documentation dependancies
      run: sudo apt install doxygen &&
           sudo apt install python3-sphinx &&
           sudo apt install breathe-doc
    - name: configure
      run: mkdir build && cd build &&
           cmake -DCMAKE_CXX_COMPILER=g++-10 -DBENCODE_BUILD_TESTS=ON ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
